<!ELEMENT population (person+)>

<!ELEMENT person (attributes?, plan+)>
<!ATTLIST person id CDATA #REQUIRED>

<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute name CDATA #REQUIRED class CDATA #IMPLIED>

<!ELEMENT plan (activity|leg|route|attributes)*>
<!ATTLIST plan selected (yes|no) #IMPLIED score CDATA #IMPLIED>

<!ELEMENT activity EMPTY>
<!ATTLIST activity type CDATA #REQUIRED
    x CDATA #IMPLIED
    y CDATA #IMPLIED
    link CDATA #IMPLIED
    facility CDATA #IMPLIED
    start_time CDATA #IMPLIED
    end_time CDATA #IMPLIED
    max_dur CDATA #IMPLIED>

<!ELEMENT leg (route?)>
<!ATTLIST leg mode CDATA #REQUIRED
    dep_time CDATA #IMPLIED
    trav_time CDATA #IMPLIED
    arr_time CDATA #IMPLIED>

<!ELEMENT route (#PCDATA)>
<!ATTLIST route type CDATA #IMPLIED
    startLink CDATA #IMPLIED
    endLink CDATA #IMPLIED
    trav_time CDATA #IMPLIED
    distance CDATA #IMPLIED>
